SELECT ROUND(AVG(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE)*100,2) AS IMMEDIATE_PERCENTAGE
FROM DELIVERY
WHERE (CUSTOMER_ID, ORDER_DATE) 
IN (SELECT CUSTOMER_ID, MIN(ORDER_DATE) FROM DELIVERY GROUP BY CUSTOMER_ID)


SELECT ROUND(SUM(CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS IMMEDIATE_PERCENTAGE
FROM DELIVERY
WHERE (CUSTOMER_ID, ORDER_DATE) 
IN (SELECT CUSTOMER_ID, MIN(ORDER_DATE) FROM DELIVERY GROUP BY CUSTOMER_ID)


WITH RANKED_ORDERS AS (
    SELECT *,
           ROW_NUMBER() OVER(
               PARTITION BY CUSTOMER_ID
               ORDER BY ORDER_DATE ASC
           ) AS RN
    FROM DELIVERY
)
SELECT
    ROUND(
        AVG(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE) * 100,
        2
    ) AS IMMDIATE_PERCENTAGE
FROM RANKED_ORDERS
WHERE RN = 1;
