WITH FIRST_LOGIN AS (
SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIN_DATE 
FROM ACTIVITY 
GROUP BY PLAYER_ID )

SELECT ROUND(COUNT(A.PLAYER_ID)/(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2) AS FRACTION FROM ACTIVITY AS A
JOIN FIRST_LOGIN AS F
ON A.PLAYER_ID = F.PLAYER_ID AND A.EVENT_DATE = DATE_ADD(F.FIRST_LOGIN_DATE, INTERVAL 1 DAY)    